# Use official Node.js image
FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy all frontend files
COPY . .

# Build Next.js app
RUN npm run build

# Expose frontend port
EXPOSE 5000

# Start frontend
CMD ["npm", "run", "start"]