version: "3.9"

services:
  frontend:
    build: ./apps/frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000

  backend:
    build: ./apps/backend
    ports:
      - "3000:3000"
    depends_on:
      - ml
    environment:
      - ML_URL=http://ml:8000

  ml:
    build: ./apps/ml
    ports:
      - "8000:8000"